----------------------------------------------
-- Export file for user C##DEVELOPER@ORCL   --
-- Created by daxte on 29.09.2017, 13:52:35 --
----------------------------------------------

set define off
spool FInal_DB_script.log

prompt
prompt Creating table IB_D_ACCOUNT_TYPE
prompt ================================
prompt
create table IB_D_ACCOUNT_TYPE
(
  id                NUMBER(8) generated by default as identity,
  account_type_name VARCHAR2(50) not null,
  interest_rate     NUMBER(8,2) not null
)
;
alter table IB_D_ACCOUNT_TYPE
  add constraint PK_ACCOUNT_TYPE primary key (ID);

prompt
prompt Creating table IB_D_CURRENCY
prompt ============================
prompt
create table IB_D_CURRENCY
(
  id            NUMBER(8) generated by default as identity,
  symbol        VARCHAR2(10) not null,
  currency_name VARCHAR2(50) not null
)
;
alter table IB_D_CURRENCY
  add constraint PK_CURRENCY primary key (ID);

prompt
prompt Creating table IB_ACCOUNT
prompt =========================
prompt
create table IB_ACCOUNT
(
  id                NUMBER(8) generated by default as identity,
  account_type_c_id NUMBER(8) not null,
  currency_c_id     NUMBER(8) not null,
  account_name      VARCHAR2(50) not null,
  balance           NUMBER(8,2) not null,
  account_prefix    VARCHAR2(6),
  account_number    VARCHAR2(10) not null
)
;
alter table IB_ACCOUNT
  add constraint PK_ACCOUNT primary key (ID);
alter table IB_ACCOUNT
  add constraint FK_ACCOUNT_ACCOUNT_TYPE foreign key (ACCOUNT_TYPE_C_ID)
  references IB_D_ACCOUNT_TYPE (ID);
alter table IB_ACCOUNT
  add constraint FK_ACCOUNT_CURRENCY foreign key (CURRENCY_C_ID)
  references IB_D_CURRENCY (ID);
alter table IB_ACCOUNT
  add constraint CHECK_ACCOUNT_NUMBER_A
  check (TRANSLATE(ACCOUNT_NUMBER , 'A0123456789','A') IS NULL);
alter table IB_ACCOUNT
  add constraint CHECK_ACCOUNT_PREFIX_A
  check (TRANSLATE(ACCOUNT_PREFIX , 'A0123456789','A') IS NULL);

prompt
prompt Creating table IB_D_COUNTRY
prompt ===========================
prompt
create table IB_D_COUNTRY
(
  id           NUMBER(8) generated by default as identity,
  country_name VARCHAR2(100) not null
)
;
alter table IB_D_COUNTRY
  add constraint PK_D_COUNTRY primary key (ID);

prompt
prompt Creating table IB_ADDRESS
prompt =========================
prompt
create table IB_ADDRESS
(
  id            NUMBER(8) generated by default as identity,
  country_id    NUMBER(8) not null,
  city          VARCHAR2(100) not null,
  street        VARCHAR2(100) not null,
  street_number VARCHAR2(50),
  zip_code      VARCHAR2(50)
)
;
alter table IB_ADDRESS
  add constraint PK_ADDRESS primary key (ID);
alter table IB_ADDRESS
  add constraint FK_IB_ADDRESS_IB_D_COUNTRY foreign key (COUNTRY_ID)
  references IB_D_COUNTRY (ID);

prompt
prompt Creating table IB_CLIENT
prompt ========================
prompt
create table IB_CLIENT
(
  id                   NUMBER(8) generated by default as identity,
  residence_address_id NUMBER(8) not null,
  first_name           VARCHAR2(100) not null,
  last_name            VARCHAR2(100) not null,
  personal_number      VARCHAR2(50) not null,
  email                VARCHAR2(50) not null,
  telephone_number     VARCHAR2(50) not null,
  sso_id               VARCHAR2(30) not null,
  password             VARCHAR2(100) not null,
  state                VARCHAR2(30) not null
)
;
alter table IB_CLIENT
  add constraint PK_CLIENT primary key (ID);
alter table IB_CLIENT
  add constraint UQ_CLIENT unique (SSO_ID);
alter table IB_CLIENT
  add constraint FK_CLIENT_RESIDENCE_ADDRESS foreign key (RESIDENCE_ADDRESS_ID)
  references IB_ADDRESS (ID);

prompt
prompt Creating table IB_D_BANK
prompt ========================
prompt
create table IB_D_BANK
(
  id        NUMBER(8) generated by default as identity,
  code      VARCHAR2(4) not null,
  bank_name VARCHAR2(100) not null,
  swift     VARCHAR2(20) not null
)
;
alter table IB_D_BANK
  add constraint PK_BANK primary key (ID);

prompt
prompt Creating table IB_PAYMENT_INFO
prompt ==============================
prompt
create table IB_PAYMENT_INFO
(
  id                   NUMBER(8) generated by default as identity,
  account_prefix       VARCHAR2(6),
  account_number       VARCHAR2(10) not null,
  amount               NUMBER(8,2) not null,
  variable_symbol      VARCHAR2(10),
  constant_symbol      VARCHAR2(10),
  message_to_recipient VARCHAR2(50),
  specific_symbol      VARCHAR2(10),
  bank_id              NUMBER(8) not null
)
;
alter table IB_PAYMENT_INFO
  add constraint PK_PAYMENT_INFO primary key (ID);
alter table IB_PAYMENT_INFO
  add constraint PK_PAYMENT_INFO_BANK foreign key (BANK_ID)
  references IB_D_BANK (ID);
alter table IB_PAYMENT_INFO
  add constraint CHECK_ACCOUNT_NUMBER_PI
  check (TRANSLATE(ACCOUNT_NUMBER , 'A0123456789','A') IS NULL);
alter table IB_PAYMENT_INFO
  add constraint CHECK_ACCOUNT_PREFIX_PI
  check (TRANSLATE(ACCOUNT_PREFIX , 'A0123456789','A') IS NULL);

prompt
prompt Creating table IB_ACCOUNT_FAVOURITE
prompt ===================================
prompt
create table IB_ACCOUNT_FAVOURITE
(
  id                     NUMBER(8) generated by default as identity,
  client_id              NUMBER(8) not null,
  payment_info_id        NUMBER(8) not null,
  account_favourite_name VARCHAR2(50) not null
)
;
alter table IB_ACCOUNT_FAVOURITE
  add constraint PK_ACOUNT_FAVOURITE primary key (ID);
alter table IB_ACCOUNT_FAVOURITE
  add constraint FK_ACCOUNT_FAV_PAY_INFO foreign key (PAYMENT_INFO_ID)
  references IB_PAYMENT_INFO (ID);
alter table IB_ACCOUNT_FAVOURITE
  add constraint FK_ACOUNT_FAVOURITE_CLIENT foreign key (CLIENT_ID)
  references IB_CLIENT (ID);

prompt
prompt Creating table IB_ANNOUNCEMENT
prompt ==============================
prompt
create table IB_ANNOUNCEMENT
(
  id          NUMBER(8) generated by default as identity,
  importance  NUMBER(8) not null,
  header      VARCHAR2(50) not null,
  main_text   VARCHAR2(1000) not null,
  insert_date DATE not null
)
;
alter table IB_ANNOUNCEMENT
  add constraint PK_ANNOUNCEMENT primary key (ID);
alter table IB_ANNOUNCEMENT
  add constraint CHECK_IMPORTANCE
  check (importance in (1,2,3));

prompt
prompt Creating table IB_CARD
prompt ======================
prompt
create table IB_CARD
(
  id                 NUMBER(8) generated by default as identity,
  account_id         NUMBER(8) not null,
  card_number        VARCHAR2(16) not null,
  security_code      VARCHAR2(3) not null,
  validity_to        DATE not null,
  active_flag        NUMBER not null,
  day_withdraw_limit NUMBER not null,
  day_pay_limit      NUMBER not null
)
;
alter table IB_CARD
  add constraint PK_CARD primary key (ID);
alter table IB_CARD
  add constraint FK_CARD_ACCOUNT foreign key (ACCOUNT_ID)
  references IB_ACCOUNT (ID);
alter table IB_CARD
  add constraint CHECK_CARD_NUMBER
  check (TRANSLATE(CARD_NUMBER , 'A0123456789','A') IS NULL);
alter table IB_CARD
  add constraint CHECK_SECURITY_CODE
  check (TRANSLATE(SECURITY_CODE , 'A0123456789','A') IS NULL);

prompt
prompt Creating table IB_M_CLIENT_ACCOUNT
prompt ==================================
prompt
create table IB_M_CLIENT_ACCOUNT
(
  id         NUMBER(8) generated by default as identity,
  account_id NUMBER(8) not null,
  client_id  NUMBER(8) not null
)
;
alter table IB_M_CLIENT_ACCOUNT
  add constraint PK_CLIENT_ACCOUNT primary key (ID);
alter table IB_M_CLIENT_ACCOUNT
  add constraint FK_CLIENT_ACCOUNT_M_ACCOUNT foreign key (ACCOUNT_ID)
  references IB_ACCOUNT (ID);
alter table IB_M_CLIENT_ACCOUNT
  add constraint FK_CLIENT_ACCOUNT_M_CLIENT foreign key (CLIENT_ID)
  references IB_CLIENT (ID);

prompt
prompt Creating table IB_USER_PROFILE
prompt ==============================
prompt
create table IB_USER_PROFILE
(
  id   NUMBER(8) generated by default as identity,
  type VARCHAR2(30) not null
)
;
alter table IB_USER_PROFILE
  add constraint PK_USER_PROFILE primary key (ID);
alter table IB_USER_PROFILE
  add constraint UQ_USER_PROFILE_TYPE unique (TYPE);

prompt
prompt Creating table IB_M_USER_USER_PROFILE
prompt =====================================
prompt
create table IB_M_USER_USER_PROFILE
(
  id              NUMBER(8) generated by default as identity,
  client_id       NUMBER(8) not null,
  user_profile_id NUMBER(8) not null
)
;
alter table IB_M_USER_USER_PROFILE
  add constraint PK_M_USER_USER_PROFILE primary key (ID);
alter table IB_M_USER_USER_PROFILE
  add constraint FK_IB_M_USER_PROFILE foreign key (USER_PROFILE_ID)
  references IB_USER_PROFILE (ID);
alter table IB_M_USER_USER_PROFILE
  add constraint FK_M_USER_CLIENT foreign key (CLIENT_ID)
  references IB_CLIENT (ID);

prompt
prompt Creating table IB_PAYMENT
prompt =========================
prompt
create table IB_PAYMENT
(
  id              NUMBER(8) generated by default as identity,
  from_account_id NUMBER(8) not null,
  to_account_id   NUMBER(8) not null,
  payment_info_id NUMBER(8) not null,
  payment_date    DATE not null
)
;
alter table IB_PAYMENT
  add constraint PK_PAYMENT primary key (ID);
alter table IB_PAYMENT
  add constraint FK_PAYMENT_FROM_ACCOUNT foreign key (FROM_ACCOUNT_ID)
  references IB_ACCOUNT (ID);
alter table IB_PAYMENT
  add constraint FK_PAYMENT_PAYMENT_INFO foreign key (PAYMENT_INFO_ID)
  references IB_PAYMENT_INFO (ID);
alter table IB_PAYMENT
  add constraint FK_PAYMENT_TO_ACCOUNT foreign key (TO_ACCOUNT_ID)
  references IB_ACCOUNT (ID);

prompt
prompt Creating table IB_PAYMENT_SCHEDULED
prompt ===================================
prompt
create table IB_PAYMENT_SCHEDULED
(
  id              NUMBER(8) generated by default as identity,
  account_id      NUMBER(8) not null,
  payment_info_id NUMBER(8) not null,
  periode         VARCHAR2(10) not null,
  payment_date    DATE not null,
  end_date        DATE
)
;
alter table IB_PAYMENT_SCHEDULED
  add constraint PK_SHEDULED_PAYMENT primary key (ID);
alter table IB_PAYMENT_SCHEDULED
  add constraint FK_PAYMENT_SCHEDULED_ACCOUNT foreign key (ACCOUNT_ID)
  references IB_ACCOUNT (ID);
alter table IB_PAYMENT_SCHEDULED
  add constraint FK_PAYMENT_SCHE_PAY_INFO foreign key (PAYMENT_INFO_ID)
  references IB_PAYMENT_INFO (ID);
alter table IB_PAYMENT_SCHEDULED
  add constraint CHECK_PERIODE
  check (PERIODE IN ('MONTHLY','YEARLY'));


spool off
